import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { bookings } from '../../mock/fixtures';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
const Agenda = () => {
    const [newSlot, setNewSlot] = useState('2024-03-24T10:00');
    const [message, setMessage] = useState('');
    return (_jsxs("section", { className: "space-y-6", children: [_jsxs("header", { className: "space-y-2", children: [_jsx("h1", { className: "text-3xl font-bold text-text", children: "Mon agenda" }), _jsx("p", { className: "text-sm text-subtext", children: "Ouvrez ou bloquez des cr\u00E9neaux, synchronis\u00E9s automatiquement avec la recherche parents." })] }), _jsxs("div", { className: "grid gap-6 md:grid-cols-2", children: [_jsxs("div", { className: "space-y-4 rounded-2xl border border-muted/80 bg-white p-6 shadow-card", children: [_jsx("h2", { className: "text-xl font-semibold text-text", children: "Prochains cr\u00E9neaux confirm\u00E9s" }), _jsx("ul", { className: "space-y-3 text-sm", children: bookings.map((booking) => (_jsxs("li", { className: "flex items-center justify-between rounded-lg border border-muted/60 p-3", children: [_jsxs("span", { children: [booking.date, " \u2014 ", booking.time] }), _jsx("span", { className: "text-subtext", children: booking.atHome ? 'Déplacement' : 'Salon' })] }, booking.id))) })] }), _jsxs("div", { className: "space-y-4 rounded-2xl border border-primary/20 bg-primary/5 p-6 shadow-card", children: [_jsx("h2", { className: "text-xl font-semibold text-primary", children: "G\u00E9rer mes cr\u00E9neaux" }), _jsxs("label", { className: "space-y-2 text-sm text-text", children: ["Ajouter un cr\u00E9neau", _jsx(Input, { type: "datetime-local", value: newSlot, onChange: (e) => setNewSlot(e.target.value) })] }), _jsx(Button, { className: "w-full", children: "Ouvrir ce cr\u00E9neau" }), _jsxs("label", { className: "space-y-2 text-sm text-text", children: ["Bloquer des cong\u00E9s", _jsx("textarea", { className: "min-h-[120px] w-full rounded-xl border border-muted/80 p-3", placeholder: "Indiquez vos dates d\u2019absence, nous les masquons c\u00F4t\u00E9 parents.", value: message, onChange: (e) => setMessage(e.target.value) })] }), _jsx(Button, { variant: "secondary", className: "w-full", children: "Bloquer" }), _jsx("p", { className: "text-xs text-primary", children: "Un rappel automatique avec lien Maps est envoy\u00E9 la veille \u00E0 20h." })] })] })] }));
};
export default Agenda;
