import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../components/ui/tabs';
import { bookings, stylists } from '../mock/fixtures';
import { formatCurrency } from '../lib/format';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { useI18n } from '../i18n/I18nProvider';
const Account = () => {
    const { t } = useI18n();
    const [note, setNote] = useState(5);
    const [comment, setComment] = useState('');
    return (_jsxs("section", { className: "space-y-8", children: [_jsxs("header", { className: "space-y-2", children: [_jsx("h1", { className: "text-3xl font-bold text-text", children: t('account.tabs.bookings') }), _jsx("p", { className: "text-sm text-subtext", children: "Retrouvez vos r\u00E9servations, cartes enregistr\u00E9es et param\u00E8tres." })] }), _jsxs(Tabs, { defaultValue: "bookings", children: [_jsxs(TabsList, { children: [_jsx(TabsTrigger, { value: "bookings", children: t('account.tabs.bookings') }), _jsx(TabsTrigger, { value: "favorites", children: t('account.tabs.favorites') }), _jsx(TabsTrigger, { value: "payments", children: t('account.tabs.payments') }), _jsx(TabsTrigger, { value: "settings", children: t('account.tabs.settings') })] }), _jsx(TabsContent, { value: "bookings", className: "space-y-6", children: bookings.map((booking) => {
                            const stylist = stylists.find((s) => s.id === booking.stylistId);
                            const service = stylist?.services.find((srv) => srv.id === booking.serviceId);
                            return (_jsxs("article", { className: "rounded-2xl border border-muted/80 bg-white p-6 shadow-card", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-4", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-xl font-semibold text-text", children: stylist?.name }), _jsxs("p", { className: "text-sm text-subtext", children: [booking.date, " \u00E0 ", booking.time, " \u2014 ", booking.atHome ? 'À domicile' : 'Chez la coiffeuse'] })] }), _jsxs("div", { className: "text-right", children: [_jsx("p", { className: "text-sm text-subtext", children: service?.title }), _jsx("p", { className: "text-base font-semibold text-text", children: formatCurrency(service?.price ?? 0) })] })] }), booking.status === 'completed' && (_jsxs("div", { className: "mt-4 space-y-3 rounded-xl border border-primary/20 bg-primary/5 p-4", children: [_jsx("h3", { className: "text-sm font-semibold text-primary", children: t('account.reviews.cta') }), _jsxs("label", { className: "flex items-center gap-2 text-sm text-text", children: [t('account.reviews.ratingLabel'), _jsx(Input, { type: "number", min: 1, max: 5, value: note, onChange: (e) => setNote(Number(e.target.value)), className: "w-20" })] }), _jsx("textarea", { className: "min-h-[100px] w-full rounded-xl border border-muted/80 p-3 text-sm", placeholder: t('account.reviews.commentLabel'), value: comment, onChange: (e) => setComment(e.target.value) }), _jsx(Button, { className: "w-full md:w-auto", children: t('account.reviews.submit') })] }))] }, booking.id));
                        }) }), _jsx(TabsContent, { value: "favorites", children: _jsx("p", { className: "text-sm text-subtext", children: "Vous n\u2019avez pas encore de favoris. Ajoutez des coiffeuses pour les retrouver facilement." }) }), _jsx(TabsContent, { value: "payments", children: _jsx("div", { className: "rounded-2xl border border-muted/80 bg-white p-6 shadow-card text-sm text-subtext", children: _jsx("p", { children: "Aucune carte sauvegard\u00E9e. Ajoutez-en lors de votre prochaine r\u00E9servation." }) }) }), _jsx(TabsContent, { value: "settings", children: _jsxs("div", { className: "space-y-3 text-sm text-subtext", children: [_jsx("p", { children: "Modifiez votre adresse, vos pr\u00E9f\u00E9rences de contact et g\u00E9rez vos notifications ici." }), _jsx(Button, { variant: "secondary", className: "w-full md:w-auto", children: "Mettre \u00E0 jour mon profil" })] }) })] })] }));
};
export default Account;
