import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { MapPin, Star } from 'lucide-react';
import { Card, CardContent } from '../ui/card';
import { TrustBadge } from '../common/Badges';
import { Button } from '../ui/button';
export const StylistCard = ({ stylist, onClick }) => {
    const primaryService = stylist.services[0];
    return (_jsx(Card, { className: "flex flex-col gap-4 p-4 transition hover:-translate-y-1 hover:shadow-lg focus-within:ring-2 focus-within:ring-primary", children: _jsxs(CardContent, { className: "flex flex-col gap-4 p-0", children: [_jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-xl font-semibold text-text", children: stylist.name }), _jsxs("div", { className: "mt-2 flex flex-wrap gap-2", children: [stylist.kidFriendly && _jsx(TrustBadge, { variant: "KidFriendly" }), stylist.verifiedID && _jsx(TrustBadge, { variant: "VerifiedID" }), stylist.rating >= 4.8 && _jsx(TrustBadge, { variant: "TopRated" })] })] }), _jsxs("div", { className: "flex flex-col items-end text-right", children: [_jsxs("span", { className: "flex items-center gap-1 text-sm font-semibold text-primary", children: [_jsx(Star, { className: "h-4 w-4 fill-primary text-primary", "aria-hidden": true }), stylist.rating.toFixed(1)] }), _jsxs("span", { className: "text-xs text-subtext", children: [stylist.reviewsCount, " avis"] })] })] }), _jsxs("div", { className: "flex flex-wrap items-center gap-3 text-sm text-subtext", children: [_jsx(MapPin, { className: "h-4 w-4", "aria-hidden": true }), _jsxs("span", { children: [stylist.city, " \u2022 ", stylist.distanceKm.toFixed(1), " km"] })] }), primaryService && (_jsxs("div", { className: "rounded-lg bg-muted px-3 py-2 text-sm", children: [_jsx("p", { className: "font-semibold text-text", children: primaryService.title }), _jsxs("p", { className: "text-subtext", children: [primaryService.price, " \u20AC \u2022 ", primaryService.durationMin, " min"] }), stylist.kidFriendly && _jsx("p", { className: "mt-1 text-xs text-success", children: "98% des parents recommandent" })] })), _jsx(Button, { type: "button", onClick: onClick, className: "w-full md:w-auto", children: "Voir le profil" })] }) }));
};
